-- MySQL Script generated by MySQL Workbench
-- Thu Apr  8 23:25:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema qztech_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema qztech_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `qztech_db` DEFAULT CHARACTER SET utf8 ;
USE `qztech_db` ;

-- -----------------------------------------------------
-- Table `qztech_db`.`usersRol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qztech_db`.`usersRol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `roltype` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qztech_db`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qztech_db`.`image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(45) NOT NULL,
  `description` VARCHAR(600)  NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qztech_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qztech_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(400) NOT NULL,
  `isverified` TINYINT NULL,
  `userrolid` INT NULL,
  `socialid` INT NULL,
  `provider` VARCHAR(45) NULL,
  `imageid` INT NULL,
  `active` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `userrolid_idx` (`userrolid` ASC),
  INDEX `imageid_idx` (`imageid` ASC),
  CONSTRAINT `userrolid`
    FOREIGN KEY (`userrolid`)
    REFERENCES `qztech_db`.`usersRol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `imageid`
    FOREIGN KEY (`imageid`)
    REFERENCES `qztech_db`.`image` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qztech_db`.`usersContact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qztech_db`.`usersContact` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userid` INT NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `number` INT NOT NULL,
  `floor` VARCHAR(45) NULL,
  `phonenumber` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `userid_idx` (`userid` ASC),
  CONSTRAINT `userid`
    FOREIGN KEY (`userid`)
    REFERENCES `qztech_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qztech_db`.`productsType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qztech_db`.`productsType` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  `detail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qztech_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qztech_db`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `productstypedid` INT NOT NULL,
  `description` VARCHAR(600) NOT NULL,
  `price` INT NOT NULL,
  `potency` INT NOT NULL,
  `autonomy` INT NOT NULL,
  `security` VARCHAR(45) NOT NULL,
  `active` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `producttypeid_idx` (`productstypedid` ASC),
  CONSTRAINT `producttypeid`
    FOREIGN KEY (`productstypedid`)
    REFERENCES `qztech_db`.`productsType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qztech_db`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qztech_db`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `orderuserid` INT NOT NULL,
  `orderproductid` INT NOT NULL,
  `quantity` INT NULL,
  `datecreated` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `orderproductid_idx` (`orderproductid` ASC),
  INDEX `orderuserid_idx` (`orderuserid` ASC),
  CONSTRAINT `orderuserid`
    FOREIGN KEY (`orderuserid`)
    REFERENCES `qztech_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `orderproductid`
    FOREIGN KEY (`orderproductid`)
    REFERENCES `qztech_db`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qztech_db`.`ordersState`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qztech_db`.`ordersState` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ordersid` INT NOT NULL,
  `confirmed` INT NULL,
  `departure` INT NULL,
  `delivery` INT NULL,
  `payed` INT NULL,
  `cancel` INT NULL,
  `departuredate` DATETIME NULL,
  `confirmationdate` DATETIME NULL,
  `deliverydate` DATETIME NULL,
  `canceldate` DATETIME NULL,
  `methodpayment` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ordersid_idx` (`ordersid` ASC),
  CONSTRAINT `ordersid`
    FOREIGN KEY (`ordersid`)
    REFERENCES `qztech_db`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qztech_db`.`productsStock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qztech_db`.`productsStock` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `stockproductid` INT NOT NULL,
  `availability` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `stockproductid_idx` (`stockproductid` ASC),
  CONSTRAINT `stockproductid`
    FOREIGN KEY (`stockproductid`)
    REFERENCES `qztech_db`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qztech_db`.`productImage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qztech_db`.`productImage` (
  `id` INT NOT NULL,
  `prodid` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `imagid` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `prodid`
    FOREIGN KEY (`prodid`)
    REFERENCES `qztech_db`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `imagid`
    FOREIGN KEY (`imagid`)
    REFERENCES `qztech_db`.`image` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
